# Example config for first search in distributed search setup
# Used for "predict_library" and "first search" steps
# (Default settings are suitable for the first search, except the multi-step search which has to be deactivated)
general:
  # Enables separate MBR step, not applicable for first search (This must be set to false for distributed first search configs)
  mbr_step_enabled: false
  # whether to reuse previously calculated quantification data
  reuse_quant: false
  # whether to save the output (mbr) library to the output directory
  save_mbr_library: True

search:
  # target ms1 tolerance in ppm
  target_ms1_tolerance: 15
  # target ms2 tolerance in ppm
  target_ms2_tolerance: 15
  # target retention time tolerance in seconds if > 1, or a proportion of the total gradient length if < 1. 0.0 means to optimize automatically
  target_rt_tolerance: 0.0 # default is to optimize automatically
  # target ion mobility tolerance in 1/K_0
  target_mobility_tolerance: 0.0 # default is to optimize automatically
  # Quant window
  quant_window: 3