# config used for "mbr", "second search" and "lfq" steps
fdr:
  inference_strategy: library # do not change for "second search"
search:
  target_num_candidates: 5 # do not change for "second search"
general:
  mbr_step_enabled: false # do not change for "second search"

search:
  # target ms1 tolerance in ppm
  target_ms1_tolerance: 15
  # target ms2 tolerance in ppm
  target_ms2_tolerance: 15
  # target retention time tolerance in seconds if > 1, or a proportion of the total gradient length if < 1. 0.0 means to optimize automatically
  target_rt_tolerance: 0.0 # default is to optimize automatically
  # target ion mobility tolerance in 1/K_0
  target_mobility_tolerance: 0.0 # default is to optimize automatically
  # Quant window
  quant_window: 3